<?php


namespace common\components;


use yii\base\Component;

/**
 *
 * Class AssetsDownload
 * @property-read $head
 * @property-read $body
 * @property-read $assets
 * @package common\components
 */
class AssetsDownload extends Component
{

    public  $url ='';
    public  $basePath ='@vendor/bower-asset';
    public  $assetName ='';
    private $_body='';
    private $_header='';

    public function init(){
       // $this->_curl = curl_init();
        //parent::init(); // TODO: Change the autogenerated stub
    }


    public function open(){
        $UserAgent = 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0; SLCC1; .NET CLR 2.0.50727; .NET CLR 3.0.04506; .NET CLR 3.5.21022; .NET CLR 1.0.3705; .NET CLR 1.1.4322)';
        $curl = curl_init();;
        curl_setopt($curl, CURLOPT_URL, $this->url);
        curl_setopt($curl, CURLOPT_HEADER, 1);  //0表示不输出Header，1表示输出
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
        curl_setopt($curl, CURLOPT_ENCODING, '');
        curl_setopt($curl, CURLOPT_USERAGENT, $UserAgent);
        curl_setopt($curl, CURLOPT_FOLLOWLOCATION, 1);
        $data = curl_exec($curl);
        if ($data === FALSE) {
            return "cURL Error: " . curl_error($curl);
        }
        return curl_getinfo($curl, CURLINFO_HEADER_OUT);

    }
    public function close(){

    }

    public function getBody(){}
    public function getHead(){  return $this->_header;}



    /**
     * @return mixed
     */
    public function getAssets(){
        preg_match_all('/(?:href|src)="(.*?[css|js])"/', $this->body, $matchs);
        return $matchs;
    }



}