<?php


namespace common\components;

use AlibabaCloud\Client\AlibabaCloud;
use AlibabaCloud\Client\Exception\ClientException;
use AlibabaCloud\Client\Exception\ServerException;
use AlibabaCloud\Dysmsapi\Dysmsapi;
use yii\base\Component;

/**
 * Class Dysms
 * @property-read $client 连接对象
 * @package common\components
 */
class Dysms extends Component
{
    public  $accessKeyId  ='LTAI4FfSwZDjYp7Psn1w2jbz';
    public  $accessKeySecret  ='pDO7yeJ1DaoMEJjWXxJB9lGYdzUCrw';
    private $_client;
    //短信签名名称
    public $SignName ="元亨娱乐";
    //短信模板CODE
    public  $TemplateCode="SMS_174991330";
    public $TemplateParam="{code:{\$code}}";
    private $_Client;

    /**
     * 初始化链接对象
     */
    public function init(){
        parent::init(); // TODO: Change the autogenerated stub
       $this->_client= AlibabaCloud::accessKeyClient($this->accessKeyId, $this->accessKeySecret)
            ->regionId('cn-hangzhou')
            ->asDefaultClient();
    }
    /**
     * @return mixed
     */
    public function getClient(){
        return $this->_client;
    }
    public function sendCode($phone,$code){
        AlibabaCloud::accessKeyClient($this->accessKeyId, $this->accessKeySecret)
            ->regionId('cn-hangzhou')
            ->asDefaultClient();
        $request = Dysmsapi::v20170525()->sendSms();
        $result = $request
            ->withPhoneNumbers($phone)
            ->withSignName($this->SignName)
            ->withTemplateCode($this->TemplateCode)
            ->withTemplateParam("{code:{".$code."}}")
            ->debug(true) // Enable the debug will output detailed information
            ->connectTimeout(1) // Throw an exception when Connection timeout
            ->timeout(1) // Throw an exception when timeout
            ->request();
        return $result;
    }
}
