<?php


namespace common\components;

use Yii;
use Exception;
use yii\base\Component;
use ipinfo\ipinfo\IPinfo as http;
use common\models\ar\Ip  as ipModel;

/**
 * Class Ip
 * @package common\components
 */
class Ip extends  Component
{

    public $token = "7265d1b29d49c2";
    public $allowedIPs = ['127.0.0.1', '::1'];
    public $ip ='';

    public function init(){
        parent::init(); // TODO: Change the autogenerated stub
        if(! Yii::$app->user->isGuest){
            $this->ip = Yii::$app->request->getUserIP();
        }
    }

    /**
     * @param $ip
     * @return array|false
     */
    public function analysis($ip){
        $client = new http($this->token);
        try{
            return $client->getRequestDetails($ip);
        }catch (Exception $exception){
            return false;
        }
    }

    /**
     * 获取所有地区的访问量
     * @return array|false
     */
    public function visitsDataByCountry(){
       $model = new ipModel();
       return $model->visitsDataByCountry();
    }

    /**
     * 获取所有登陆的城市
     * @return array|false
     */
    public function visitsDataByCity(){
        $model = new ipModel();
        return $model->visitsDataByCountry();
    }
}