<?php


namespace api\controllers;


use api\models\User;
use Yii;
use yii\web\Request;
use api\models\SignupForm;
use api\models\ApiLoginForm;
use yii\rest\ActiveController;

/**
 *
 * 用户管理 注册 登陆 退出
 * @package api\controllers
 */
class UserController extends ActiveController
{
    public $modelClass ='api\models\Module';


    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        $action= parent::actions(); // TODO: Change the autogenerated stub
        unset($action['index']);
        unset($action['create']);
        unset($action['update']);
        unset($action['delete']);
        return $action; // TODO: Change the autogenerated stub
    }

    /**
     * 登陆返回token
     * @return ApiLoginForm|array
     * @throws yii\base\InvalidConfigException
     */
    public function actionLogin(){
        $request = new Request();
        $model = new ApiLoginForm();
        $model->load($request->getBodyParams(),'');
        if($model->login()){
            return ['token'=>$model->login()];
        }else{
            $model->validate();
            return $model;
        }
    }

    /**
     * 用户注册
     * @return array SignupForm
     * @throws yii\base\InvalidConfigException
     */
    public function actionSignup(){
        $request = new Request();
        $model = new SignupForm();
        $model->load($request->getBodyParams(),'');
        if($model->signup()){
            return ['message'=>'注册成功，请前往邮箱验证','url'=>$model->verificationToken()];
        }else{
            $model->validate();
            return $model;
        }
    }

    /**
     * {@inheritdoc}
     */
    public function actionLogout(){
        $id = Yii::$app->user->id;
        if($id){
            $user = User::findOne($id);
            if($user->logout()){
                return ['message'=>'注销成功'];
            }else{
                return ['message'=>'异常'];
            }

        }
        return ['message'=>'异常asd'];
    }
}